# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        '/:year/:month/:title.html'

# Setup
title:            'Paul Ramsey'
tagline:          'Open source IT'
description:      'Open source software developer and information technology professional.<br/>Occasional blowhard.'
url:              'http://blog.cleverelephant.ca'
images:           '/images/'

author:
  name:           'Paul Ramsey'
  email:          'pramsey@cleverelephant.ca'
  telephone:      '1 250 885 0632'
  url:            'http://blog.cleverelephant.ca'
  twitter_handle: '@pwramsey'
  twitter:        'http://twitter.com/pwramsey'
  github:         'http://github.com/pramsey'
  linkedin:       'http://linkedin.com/in/paul-ramsey-717134'
  mastodon:       'https://mastodon.social/@pwramsey'

plugins: [jekyll-paginate]

gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

paginate:         5
